### ISSUE TITLE
Fatal error after upgrade to 2.2.0-rc1 due to IndexManagerController

### ISSUE THREAD

**Issue by Mark-H** [josht/faqMan#40]
````
Fatal error: Uncaught Error: Class 'IndexManagerController' not found in core/model/modx/modmanagerresponse.class.php:190 Stack trace:

#0 core/model/modx/modmanagerresponse.class.php(78): modManagerResponse->instantiateController('IndexManagerCon...', 'getInstanceDepr...') 
#1 core/model/modx/modmanagerrequest.class.php(187): modManagerResponse->outputContent(Array) 
#2 core/model/modx/modmanagerrequest.class.php(135): modManagerRequest->prepareResponse() 
#3 manager/index.php(59): modManagerRequest->handleRequest() 
#4 {main} thrown in core/model/modx/modmanagerresponse.class.php on line 190
````

**Comment by Mark-H** [comment]
It looks like you've refactored the controllers (yay). I suspect the upgrade will need to clean up some old files and/or update the menu record. 

When I visit `/manager/?a=index&namespace=faqman` it works, but the menu still points to `/manager/?a=86` on this site.

**Comment by josht** [comment]
Doh! Yep, that's exactly it.

**Comment by josht** [comment]
Fixed in rc2
